const url = 'https://5lldpsml-3000.uks1.devtunnels.ms'

export const telexGeneratedConfig = {
  data: {
    date: {
      created_at: '2025-02-17',
      updated_at: '2025-02-17',
    },
    integration_category: 'AI & Machine Learning',
    integration_type: 'modifier',
    descriptions: {
      app_name: 'AI Safety Monitor',
      app_description:
        'An AI-powered assistant that automatically monitors and filters messages for safety concerns using AI.',
      app_logo:
        'https://res.cloudinary.com/devsource/image/upload/v1737510989/pngtree-no-cursing-sign-png-image_6610915_meqkww.png',
      app_url: url,
      background_color: '#4A90E2',
    },
    target_url: `${url}/webhook`,
    key_features: [
      'Real-time detection and filtering of harmful content',
      "Advanced AI-driven safety analysis using Google's Gemini API",
      'Customizable thresholds for profanity, spam, and sensitive data',
      'Context-aware evaluations using conversation data',
      'Seamless webhook integration for instant moderation feedback',
    ],
    settings: [
      {
        label: 'bannedWords',
        type: 'text',
        description: 'List of words to automatically block',
        default: [
          'hate',
          'racist',
          'nazi',
          'kill',
          'murder',
          'suicide',
          'terrorist',
          'bomb',
          'attack',
          'abuse',
          'harass',
          'threat',
          'violence',
          'slut',
          'whore',
          'fuck',
          'shit',
          'cunt',
          'bitch',
          'asshole',
          'bastard',
          'damn',
          'hell',
          'piss',
          'dick',
          'cock',
          'pussy',
          'fag',
          'retard',
          'idiot',
          'moron',
          'stupid',
          'loser',
          'fatso',
          'ugly',
          'crap',
          'suck',
        ],
        required: false,
      },
      {
        label: 'minSafetyScore',
        type: 'number',
        description: 'Minimum safety score (0-1) for messages to be allowed',
        default: 0.7,
        required: false,
      },
      {
        label: 'enableAICheck',
        type: 'checkbox',
        description: 'Enable AI-powered safety analysis',
        default: true,
        required: false,
      },
      {
        label: 'customPrompt',
        type: 'text',
        description: 'Custom prompt for AI safety analysis',
        default: '',
        required: false,
      },
      {
        label: 'maxMessageLength',
        type: 'number',
        description: 'Maximum allowed message length',
        default: 1000,
        required: false,
      },
      {
        label: 'geminiApiKey',
        type: 'text',
        description: 'Google Gemini API key',
        default: '',
        required: true,
      },
    ],
    endpoints: [
      {
        path: '/webhook',
        method: 'POST',
        description: 'Receives messages and returns AI-generated responses',
      },
      {
        path: '/health',
        method: 'GET',
        description: 'Health check endpoint',
      },
    ],
    is_active: true,
    author: 'JC CODER',
    version: '1.0.0',
  },
}
